---
fail_fast: false
repos:

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
  
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.14.4
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
