---
- name: Play for creating a Amrik's dev environment from zero
  hosts: localhost
  tasks:
    - name: Zsh Tasks
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml

    - name: Core-packages Tasks
      ansible.builtin.import_tasks:
        file: tasks/core-packages.yml

    - name: Git Tasks
      ansible.builtin.import_tasks:
        file: tasks/git.yml

    - name: Dotfiles Tasks
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml

    - name: Node Tasks
      ansible.builtin.import_tasks:
        file: tasks/node.yml

    - name: Dev-tools Tasks
      ansible.builtin.import_tasks:
        file: tasks/dev-tools.yml

    - name: Vim Tasks
      ansible.builtin.import_tasks:
        file: tasks/vim.yml

    - name: Kubernetes Tasks
      ansible.builtin.import_tasks:
        file: tasks/k8s.yml
