- name: Install core packages
  apt:
    name: [
            "build-essential",
            "cmake",
            "pkg-config",
            "libpthread-stubs0-dev",
            "lua5.1",
            "unzip",
            "libtool",
            "libtool-bin",
            "gettext",
            "python3-pip"
        ]
