---
- name: Install pre-commit
  ansible.builtin.apt:
    name:
      - pre-commit
  become: true

- name: Enable pre-commit on projects
  ansible.builtin.command: pre-commit install
  args:
    chdir: "{{ lookup('env', 'HOME') }}/{{ item }}"
  changed_when: true
  with_items:
    - .dotfiles
    - ansible

- name: Install java
  ansible.builtin.apt:
    name:
      - openjdk-{{ item }}-source
      - openjdk-{{ item }}-doc
      - openjdk-{{ item }}-jdk
  become: true
  with_items:
    - 8
    - 11
    - 17
