---
- name: Download Google Cloud SDK package repository signing key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add google cloud SDK package repository source
  ansible.builtin.apt_repository:
    filename: google-cloud-sdk.list
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present
  become: true

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  become: true

- name: Install kubectl
  ansible.builtin.apt:
    update_cache: true
    name: kubectl
    state: present
  become: true
