- name: Download Google Cloud SDK package repository signing key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/gcloud.gpg

- name: Add google cloud SDK package repository source
  apt_repository:
    filename: google-cloud-sdk.list
    repo: "deb [signed-by=/usr/share/keyrings/gcloud.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/gcloud.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubectl
  apt:
    update_cache: yes
    name: kubectl
    state: present

