---
- name: Make sure neovim is not installed
  ansible.builtin.file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/neovim"

- name: Get Packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    version: 1d0cf98
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Clone Neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    version: 7c8c155
    dest: "{{ lookup('env', 'HOME') }}/neovim"

- name: Build neovim
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/neovim && make -j 20
  register: make_output
  changed_when: make_output.rc == 0

- name: Install neovim
  become: true
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/neovim && make install
  register: make_output
  changed_when: make_output.rc == 0

- name: Install neovim
  ansible.builtin.command: nvim +PackerSync +qall
  register: vim_packersync
  changed_when: vim_packersync.rc == 0
