- name: Install ZSH
  apt: name=zsh

- name: Change shell to zsh
  shell: sudo chsh -s $(which zsh) $(whoami)
  register: chsh_output
  changed_when: chsh_output.rc == 0
  become: true
  become_user: amrik

- name: Check that the somefile.conf exists
  stat:
    path: /home/amrik/.oh-my-zsh
  register: oh_my_stats

- name: Get Oh-My-Zsh install script
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-installer"
    mode: '777'

- name: Run Oh-my-Zsh installer
  command: "{{ lookup('env', 'HOME') }}/.oh-my-installer"
  when: not oh_my_stats.stat.exists
  become: true
  become_user: amrik

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    version: v0.7.0
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
